### ISSUE TITLE
Spurious compile error about routes in Play 2.4.6

### ISSUE THREAD

**Issue by jmvanel** [scala-ide/scala-ide-play2#266]
Lines like this in a Controller :

    routes.Application.myService()

trigger this wrong compile error :

    not found: value routes

Running the web application with SBT is fine.
A concrete example in my code:
 https://github.com/jmvanel/semantic_forms/blob/master/scala/forms_play/app/controllers/ApplicationTrait.scala#L156

**Comment by sschaef** [comment]
Do you also run the code in Eclipse or is this just a compilation error in the editor?

**Comment by jmvanel** [comment]
Well, I never found how to run a Play! application within eclipse.
So I just noticed a compilation error in the editor.

**Comment by sschaef** [comment]
Ok, in this case it is probably similar to https://github.com/scala-ide/scala-ide-play2/pull/259

There is a good chance, that this is just another one of Plays automatic imports.

**Comment by Guidoch** [comment]
Hello,

the issue here is a bit different and was already dealt some time ago in the sbteclipse-plugin.
Basically you are missing the target/twirl/main and target/routes/main folders in your project.

These folders contain the necessary files for eclipse to know that routes and views exist.

You should use the sbteclipse-plugin together with the following option in your build.sbt:
// Compile the project before generating Eclipse files, so that generated .scala or .class files for views and routes are present
EclipseKeys.preTasks := Seq(compile in Compile)

With this, every time you run "activator eclipse", the command will compile and "stage" the changes, that is creating the target/twirl and target/routes folder, before creating the eclipse project structure.

After that, remember that you have to run the "activator eclipse" every time you create a new routes or views in your project, to have eclipse know that they exist.

I hope this helps, if I wasn't able to explain myself I'll be happy to guide you through the process.

**Comment by sschaef** [comment]
Ok, we can close this issue then. The solution to avoid such errors would be to let Scala IDE understand sbt builds, which we hopefully can finally address in the the 4.5 release.
